### PR TITLE
Remove docker apps support

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mike Sul <mike.sul@foundries.io>

### CODE REVIEW

**Review by ricardosalveti — APPROVED** [review]
LGTM, but we should have the +1 from @doanac as well.

**Review by doanac — APPROVED** [review]
Just want to make sure @mike-scott doesn't see an issue if we merge and he's converting a customer factory to compose. I *think* its good though.

**Comment by mike-sul** [comment]
@mike-scott Do you think we can merge it or it too early and might impact customers?

**Comment by mike-scott** [comment]
LGTM.  Merge away.

**Review by mike-scott — APPROVED** [review]

**Pull request merged**
