### PR TITLE
main: fix missing pacman tags

### PR DESCRIPTION
**Pull request by ldts**
Remove leftover from refactoring.

### CODE REVIEW

**Comment by mwasilew** [comment]
I guess you can add "Fixes: #43" in the commit message to close the bug.

**Comment by ldts** [comment]
> I guess you can add "Fixes: #43" in the commit message to close the bug.

thanks @mwasilew for verifying!

**Review by doanac — APPROVED** [review]

**Comment by ldts** [comment]
> @ldts - i think you should have write access to this repo now. give it a try and see.

still nothing

**Comment by doanac** [comment]
try once more. i think i have it now

**Pull request merged**
