### PR TITLE
Print log message of each error

### PR DESCRIPTION
**Pull request by mike-sul**
Iterate over each error received in the `400` response and print its message.

Signed-off-by: Mike <mike.sul@foundries.io>

### CODE REVIEW

**Review by vkhoroz — APPROVED** [review]
Thanks @mike-sul .
When I first looked at this code I had a feeling it is doing something in a wrong way...

You nailed it down.

LGTM

**Comment by mwasilew** [comment]
LGTM

**Comment by mike-sul** [comment]
> can you just include a sample of the new output in the commit message?

```
Registering device,  foobar, to factory msul-dev01.
Device UUID: a0ac798a-aaf6-44f3-89d6-45ceb1293543
Unable to create device: HTTP_400
name: ' foobar' does not match '^[a-zA-Z0-9_\\-\\.]+$'
message: Input payload validation failed
```

```
Registering device,  foobar, to factory msul-dev01.
Device UUID: 5b214e9a-214f-4769-8e75-fec818dd7e6c
Unable to create device: HTTP_400
hardware-id: 'hardware-id' is a required property
name: ' foobar' does not match '^[a-zA-Z0-9_\\-\\.]+$'
message: Input payload validation failed

```

**Comment by mike-sul** [comment]
Maybe we could add `errors` and then print error messages indented with tabs?

**Comment by mike-sul** [comment]
```
Registering device,  foobar, to factory msul-dev01.
Device UUID: c8578dca-d3b1-4e6b-9996-c810e0a1778c
Unable to create device: HTTP_400
errors:
	name: ' foobar' does not match '^[a-zA-Z0-9_\\-\\.]+$'
message: Input payload validation failed

```

**Comment by mike-sul** [comment]
```
Registering device,  foobar, to factory msul-dev01.
Device UUID: b0927200-ce28-4f02-bc10-dc0f598504a7
Unable to create device: HTTP_400
errors:
	hardware-id: 'hardware-id' is a required property
	name: ' foobar' does not match '^[a-zA-Z0-9_\\-\\.]+$'
message: Input payload validation failed

```

**Review by doanac — APPROVED** [review]
looks good. its an infinity % improvement from what we had.

**Pull request merged**
