### PR TITLE
Allow devices to be registered in an initial device-group

### PR DESCRIPTION
**Pull request by doanac**
Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Review by vkhoroz — APPROVED** [review]
Ship it!

**Comment by mike-sul** [comment]
I wonder why we don't fully support this param in factory-reg-ref https://github.com/foundriesio/factory-registration-ref/blob/dadbf5b9b1d42ea4028fa44eb8b8915ae92fea6e/registration_ref/app.py#L79.
I think if `Settings.API_TOKEN_PATH` is specified then the `group` param can be passed to the PUT /devices request that the server makes to the OTA service.

Also, in the case of auto-registration at DG it's not possible to assign a group automatically.

**Comment by doanac** [comment]
> I think if Settings.API_TOKEN_PATH is specified then the group param can be passed to the PUT /devices request that the server makes to the OTA service.

I thought about that, but I think it's going to be more common for people to want to use that token as their own internal unique way to authenticate with their reference server.

> Also, in the case of auto-registration at DG it's not possible to assign a group automatically.

Correct -that's by design. That would be a big a security problem if devices could determine their group.

I see this is controversial. Let's move on for now, if someone actually wants this behavior, it's easy for us to support or for them to fork. and in the meantime, we are making sure they aren't accidentally exposing something they didn't intend to.

**Comment by mike-sul** [comment]
Sure, I just wanted to clarify.

**Comment by doanac** [comment]
> One way to make the group auto-assignment secure would be to pass the initial group via the device certificate.

I've thought that would be a nice, easy, secure way in the past as well. We do something similar for the device owner.

**Pull request merged**
